### ISSUE TITLE
domContentLoaded 

### ISSUE THREAD

**Issue by dd1994** [121Room/Performance-Monitoring#1]
1. 搞清楚需要哪些数据，各个数据的含义，这些数据如何通过 API 或者计算得到，就是现在做的；
2. 用 phantomjs 跑一下试试，phantomjs 是个好东西，有很多值得学习的地方；
3. 写那个在线监控的前端脚本，得到那些数据。这个是最难的吧，要考虑到很多问题；
4. 数据 post 到一个后端，然后展示出来，这个偏向前端 UI 效果之类的。

**Comment by dd1994** [comment]
这个 repo https://github.com/121Room/hidan 是就是接收和展示数据用的，这个是最后做的。

**Comment by dd1994** [comment]
这个 repo 是用来测试的：https://github.com/121Room/single

**Comment by dd1994** [comment]
其余 fork 的那几个是我们需要用到的或者要学习的吧

**Comment by dd1994** [comment]
到时候画个完整的表格，把所有指标的含义，具体的判断、统计方式 这些画出来，这是第一步啊，不然自己做什么都不知道。

**Comment by fromIRIS** [comment]
现在需要统计的主要数据分为4块。
1. 白屏时间：  不管兼容的话就利用Timging的firstPaintTime
   如果要兼容的话就是head之间资源加载的时间，需要插入两段script
2. 首屏时间： 给用户看到的页面完整了， 大体上就是图片加载完成，还有body内的脚本加载完成。
3. 用户可操作时间： 就是用户能操作事件的时间。
4. 用户总加载时间： 这个用Timing的loadTime。

现在我这边不太清楚的是首屏时间对应timing里的哪一块，可操作时间对应timing的哪一块。

我们可以读一些关于`浏览器渲染`的文章，应该就能准确对应好什么数据对应浏览器渲染时的哪部分时间。

http://www.open-open.com/lib/view/open1441437555143.html

http://segmentfault.com/a/1190000002589116

http://calendar.perfplanet.com/2012/deciphering-the-critical-rendering-path/ 关于用户可交互时间 和 白屏时间的文章 极好

**Comment by fromIRIS** [comment]
<table class="table table-bordered table-striped table-condensed">
   <tr>
      <td>页面总加载时间</td>
      <td>loadTime = timing.loadEventEnd - timing.navigationStart</td>
      <td>来自timing</td>
   </tr>
   <tr>
      <td>Dom树解析时间</td>
      <td>initDomTreeTime = timing.domInteractive - timing.responseEnd</td>
      <td>来自timing</td>
   </tr>
   <tr>
      <td>首字节时间(拿到html)</td>
      <td>TTFB = timing.respondStart - timing.navigationStart</td>
      <td>自己添加</td>
   </tr>
   <tr>
      <td>执行onload回调的时间</td>
      <td>loadEventTime = timing.loadEventEnd - timing.loadEventStart</td>
      <td>来自timing</td>
   </tr>
   <tr>
      <td>白屏时间</td>
      <td>firstPaint</td>
      <td>来自timing</td>
   </tr>
   <tr>
      <td>可交互时间（domContentLoaded）</td>
      <td>interactingTime = timing.domContentLoadedEventEnd - timing.navigationStart</td>
      <td>自己添加</td>
   </tr>
   <tr>
      <td>首屏时间</td>
      <td>performance.getEntries 对其对象遍历找出加载最长的资源作为首屏时间</td>
      <td>自己添加</td>
   </tr>
</table>

**Comment by dd1994** [comment]
那个 domContentLoaded https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded 
好像不是可交互时间，文档上说 `without waiting for stylesheet` 还是白屏的吧？高性能网站那本书上提到了如果 CSS 还没加载完就是白屏，所以才要把 CSS 放前面。

**Comment by dd1994** [comment]
DOM 树解析完应该在 https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/domComplete ，文档上提到了 `parser finished its work on the main document`

**Comment by dd1994** [comment]
DOM 树开始解析应该在：https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/domLoading ，因为文档提到了 `when the parser started its work`，解析完应该在 https://developer.mozilla.org/en-US/docs/Web/API/PerformanceTiming/domInteractive ，因为上面提到了 `the parser finished its work on the main document`

**Comment by dd1994** [comment]
我悟了，终于懂浏览器是怎么工作了。

**Comment by fromIRIS** [comment]
domContentLoaded  确实是可交互时间 。jquery的$(function () {}) 就是取得domContentLoaded的事件，当head标签里的同步资源加载执行完了，浏览器就可以首次渲染了，domContentLoaded指的是domtree和cssom tree都构建完毕。

**Comment by dd1994** [comment]
@fromIRIS domContentLoaded 是 DOM 树刚构建完触发的事件，因为 JQuery 要操作 DOM 的话，必须要先等浏览器把 DOM 树构建完，所以JQuery 才会选这个时间

**Comment by dd1994** [comment]
但是可交互是指用户可交互吧？

**Comment by dd1994** [comment]
`head标签里的同步资源加载执行完了，浏览器就可以首次渲染了` 这句话不对啊，HEAD 里面的 CSS 加载又不是同步的，浏览器要等 HEAD 里 CSS 加载完才开始渲染啊，不然就是白屏，高性能网站那本书上写的很清楚啊。

**Comment by dd1994** [comment]
`DomContentLoaded指的是domtree和cssom tree都构建完毕。` 不是这样的，DomContentLoaded 是指 Dom 树构建完毕，跟 CSSOM 没有关系的。

**Comment by fromIRIS** [comment]
@dd1994  我这里的可交互时间 指的就是 页面上绑定了事件的dom可以被用户点击等操作上的交互。
同步加载的js会阻塞dom树的构建，所以在head里加载同步js的时候dom树构建不了，没办法构建head后面的body，就白屏了。而head的css没加载完肯定是白屏的。

**Comment by fromIRIS** [comment]
`不是这样的，DomContentLoaded 是指 Dom 树构建完毕，跟 CSSOM 没有关系的。` dominteractive是dom树构建完毕。http://calendar.perfplanet.com/2012/deciphering-the-critical-rendering-path/ 我感觉这篇文章讲的挺好的

**Comment by dd1994** [comment]
你的理解有问题，这篇文章 http://calendar.perfplanet.com/2012/deciphering-the-critical-rendering-path/  也有错误。

**Comment by dd1994** [comment]
先来说 dominteractive 和 DomContentLoaded 的区别和联系。

**Comment by dd1994** [comment]
关于文章里 `The document is marked as “interactive” when the user agent stops parsing the document. Meaning, the DOM tree is ready.` 这句话有解释的不清楚的地方。

首先你要理解 由 HTML 到 DOM 树分三个阶段：
1. 有词法分析器(Tokenizer) 解析原文档得到 token
2. 由语法分析器(parser) 解析 token 里得到 节点对象
3. 再把节点对象构造(constructing)成 DOM 树

**Comment by dd1994** [comment]
关于 interactive 和 DomContentLoaded 有什么区别和联系： https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState

> The state indicates that the DOMContentLoaded event has been fired.

就是说 DOM 达到 interactive 这个状态后就会触发 DOMContentLoaded 事件，这一点文档上写得这么清楚好无异议。

这也是为什么 https://developer.mozilla.org/en-US/docs/Web/Events/readystatechange 里面这段代码注释的原因：

``` js

// alternative to DOMContentLoaded
document.onreadystatechange = function () {
    if (document.readyState == "interactive") {
        initApplication();
    }
}
```

这确实可以模拟 DOMContentLoaded 事件。

**Comment by dd1994** [comment]
再来看 DOMContentLoaded 事件：https://developer.mozilla.org/en-US/docs/Web/Events/DOMContentLoaded

> The DOMContentLoaded event is fired when the initial HTML document has been completely loaded and parsed, without waiting for stylesheets, images, and subframes to finish loading. 

上面明确的说了 DOMContentLoaded  触发的时候 stylesheets 还没加载完，CSS 都没加载完哪来的 CSSOM？那篇文章说 DOM tree 和 CSSOM 在这个时候构建完毕了，所以完全是错的。

**Comment by dd1994** [comment]
必须要承认是，DOMContentLoaded 事件触发的时候，CSS 根本还没有加载完，这一点 mozilla 的文档上已经说得很清楚了。CSS 和 图片这些东西的加载在 DOMContentLoaded 事件触发到 load 事件触发这个时间段。

至于你在表格里写的：

> interactingTime = timing.domContentLoadedEventEnd - timing.navigationStart

domContentLoadedEventEnd 是指 domContentLoaded 这个事件结束的时候。

解释下这个过程：

在 domContentLoaded 触发的时候，CSS 和图片什么的没有加载完，上面已经很清楚说明了。那 domContentLoaded 事件结束的
时候，CSS 加载完了吗？

不知道。因为这取决于注册在 domContentLoaded 事件上的回调函数执行的时间，如果这个回调函数执行的足够久的话，CSS 可能就加载完了。

另外关于可交互时间，我的理解就是用户可以跟那个网页交互了，图片可能还没有加载完，但至少点击一些按钮之类的应该没有问题了。但是在 domContentLoadedEventEnd 这个时间点，甚至 CSS 都可能还没有加载玩，就是白屏的，哪来的交互？

**Comment by dd1994** [comment]
另外只有 `cssom`，不存在 `cssom tree` 这样的东西，因为 css 不是树结构的。

**Comment by dd1994** [comment]
另外关于你说的 `head标签里的同步资源加载执行完了，浏览器就可以首次渲染了`，我觉得有问题的原因：

你说的 js 在 head 里加载的时候 DOM 构建不了这个我觉得没有问题。

问题在于浏览器什么时候开始渲染，我觉得不说渲染，说绘制(painting)比较好。

我来解释一下浏览器的绘图流程(先不要管 JS，JS 确实会阻塞，这个等会再说)：
1. 解析 HTML 得到 DOM 树
2. 解析 CSS 得到 cssom
3. 将 dom 上附上前面得到的 CSS 的信息得到 renderObject 树， 再计算网页层次结构得到RenderLayer 树 ，然后还有很多很多复杂的步骤，最后在浏览器内部被表示成一个绘图上下文，用于下一步的绘制。
4. 浏览器开始绘制。这一步涉及到很多计算机图形学（光珊之类的）的东西，非常复杂，我也不懂。

所以很多浏览器在 CSS 没有加载完的时候不会开始绘制，因为如果这样做的话，等到 CSS 加载完重新计算得到绘图上下文的时候，必须再重新绘制一次，会造成所谓的`无样式闪烁`这个问题。但是如果不开始绘制的话，就会白屏（这就是 IE 的做法）

所以那句 `head标签里的同步资源加载执行完了，浏览器就可以首次渲染了` 问题在哪呢？

即使 head标签里的同步资源加载执行完了，如果 css 还没有下载完，还没有解析成 cssom，浏览器也不会开始绘制。

css 下载和解析并不是同步的，它不会阻塞，它是异步的。

所以正确的说法应该是：`head标签里的同步资源加载执行完了，所有的 CSS 也加载完了，浏览器才会开始绘制`

还有我前面说的 `DomContentLoaded 是指 Dom 树构建完毕，跟 CSSOM 没有关系的。`  也是错的，
DomContentLoaded 不是指 dom 树构建完毕，而是指 Dom 树构建完毕时触发的事件。后半句是对的，跟 CSSOM 确实没有关系，因为这时 CSS 都还没有加载完。

**Comment by dd1994** [comment]
至于  http://calendar.perfplanet.com/2012/deciphering-the-critical-rendering-path 为什么是错的，可能有两个原因：
1. 作者自己都没有搞懂
2. 这篇文章写于 2012 年，已经过时了，现在不一样了。

这也是在网络上浏览文章经常会遇到的问题，所以一切还是要看 Mozilla 的文档或者浏览器的源码。

**Comment by dd1994** [comment]
还有我前面说的 `DomContentLoaded 是指 Dom 树构建完毕，跟 CSSOM 没有关系的。`  也是错的，
DomContentLoaded 不是指 dom 树构建完毕，而是指 Dom 树构建完毕时触发的事件。后半句是对的，跟 CSSOM 确实没有关系。

**Comment by dd1994** [comment]
你可以随意打开一个网页，等他加载完以后把下面代码复制进 console:

``` js
'use strict'
console.log(`performance.timing.domInteractive: ${performance.timing.domInteractive}`)
console.log(`performance.timing.domContentLoadedEventStart: ${performance.timing.domContentLoadedEventStart}`)
console.log(`performance.timing.domContentLoadedEventEnd: ${performance.timing.domContentLoadedEventEnd}`)
console.log(`performance.timing.domComplete: ${performance.timing.domComplete}`)
console.log(`performance.timing.loadEventStart: ${performance.timing.loadEventStart}`)
console.log(`performance.timing.loadEventEnd: ${performance.timing.loadEventEnd}`)
```

我发现 `performance.timing.domInteractive` 和 `performance.timing.domContentLoadedEventStart` 总是一样的，`performance.timing.domComplete` 和 `performance.timing.loadEventStart` 也总是一样的，这就是我前面说的 DOM 达到 interactive 这个状态后就会触发 DOMContentLoaded 事件，
dom 到达 complete 状态后同理会触发 load 事件。

注意开隐身模式，把浏览器插件都禁了，插件有很多奇怪的影响。

**Comment by fromIRIS** [comment]
> The DOMContentLoaded event is fired when the initial HTML document has been completely loaded and parsed, without waiting for stylesheets, images, and subframes to finish loading.

你前面提到的多数论点，都是基于以上这句话的。
对于这句话 没有争议，存在这种情况。下图为例。
![image](https://cloud.githubusercontent.com/assets/8492963/11083990/c3456ade-8870-11e5-97ea-3c392d671311.png)
没有加载js，蓝线在css记载完之前就到了，说明在触发`domContentLoaded`事件的时候，css没加载完。此时白屏时间要大于`domContentLoaded`事件触发的时间。**无异议**
![image](https://cloud.githubusercontent.com/assets/8492963/11084147/9fd8a0b4-8872-11e5-8475-6c89f692ff32.png)

但是现在存在一种情况，js会去查询CSSOM，所以在执行同步js的之前，会等待css的下载和构建CSSOM。
具体看https://developers.google.com/web/fundamentals/performance/critical-rendering-path/analyzing-crp?hl=zh-cn
如果这个情况确实存在（我还没有验证过），那么css会阻塞js的执行（不是下载），而js的被阻塞，导致的就是domtree的构建，顺带的就导致`domContentLoaded`事件的延迟。所以那篇文章讲的`domContentLoaded`事件的触发，代表了domtree和CSSOM的准备就绪，也是正确的。

所以现在需要弄清楚css会不会阻塞js的执行，就能解决我们上面的分歧了。

**Comment by fromIRIS** [comment]
`dominteractive 和 DomContentLoaded 的区别和联系。`以及`performance.timing.domComplete 和 load的区别`我很赞同。

**Comment by fromIRIS** [comment]
http://stevesouders.com/hpws/js-middle.php  这个例子应该表明了 dom树没构建完的时候，页面已经绘制了一部分了。

**Comment by fromIRIS** [comment]
更新： 关于CSS是否会阻塞同步js的，我这边基本验证为 `是` 了。
![image](https://cloud.githubusercontent.com/assets/8492963/11094560/562493a2-88cb-11e5-9c03-7ad666376de9.png)
js早就加载完了，按你原先的说法，应该不管css加载而直接触发domContentLoaded事件了，但此时还是等到了css加载完毕，原因就是CSSOM的构建阻塞了同步js，而js又会阻塞DOMtree构建。（另外：也会阻塞defer脚本和异步脚本，下做说明）

**Comment by dd1994** [comment]
确实是这样，你说得对。
